lane :test do
  sh("echo 'PRODUCT_BUNDLE_IDENTIFIER = com.sovcharenko.app' > Test.xcconfig")

  # Read PRODUCT_BUNDLE_IDENTIFIER value from Configs/Release.xcconfig
  bundle_id = get_xcconfig_value(
    path: 'fastlane/Test.xcconfig',
    name: 'PRODUCT_BUNDLE_IDENTIFIER'
  )
  puts("Bundle ID: #{bundle_id}")

  # Sets PRODUCT_NAME value to 'App' in Configs/Test.xcconfig
  set_xcconfig_value(
    path: 'fastlane/Test.xcconfig',
    name: 'PRODUCT_NAME',
    value: 'App'
  )

  # Update PRODUCT_NAME value to 'Updated App' in Configs/Test.xcconfig
  update_xcconfig_value(
    path: 'fastlane/Test.xcconfig',
    name: 'PRODUCT_NAME',
    value: 'Updated App'
  )
end
